### ISSUE TITLE
https://prettymapp.streamlit.app/

### ISSUE THREAD

**Issue by marcolino** [chrieke/prettymapp#32] opened 2023-08-23 13:49 UTC
Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/chrieke/prettymapp/issues/new).

**Comment by falkecarlsen** [comment] 2023-08-23 14:12
Might be hug-of-death from Hackernews https://news.ycombinator.com/item?id=37222823

**Comment by chrieke** [comment] 2023-08-23 15:19
Yeah not much I can do right now, when restarting or deleting&creating the app again it goes down after 3 seconds, something is off.

Afaik the streamlit folks already increased the app memory.

**Comment by jxpsert** [comment] 2023-08-24 14:59
Duplicate of #30

**Closed** 2023-08-25 18:46 UTC
